lf: add a command fzf-file to select a file via fzf

diff --git a/.config/lf/lfrc b/.config/lf/lfrc
--- a/.config/lf/lfrc
+++ b/.config/lf/lfrc
@@ -29,174 +29,210 @@ set hidden
 
 # Override the default open for file opening (binded to 'l' by default)
 cmd open &{{
-  case $(file --mime-type "$(readlink -f $f)" -b) in
-    text/*|application/json|inode/x-empty|application/octet-stream) lf -remote "send $id \$$EDITOR \$fx";;
-    *) for f in $fx; do open $f > /dev/null 2> /dev/null & done;;
-  esac
+    case $(file --mime-type "$(readlink -f $f)" -b) in
+        text/*|application/json|inode/x-empty|application/octet-stream) lf -remote "send $id \$$EDITOR \$fx";;
+        *) for f in $fx; do open $f > /dev/null 2> /dev/null & done;;
+    esac
 }}
 
 cmd mkdir $mkdir -p "$(echo $* | tr ' ' '\ ')"
 
 # Create a directory with the selected items
 cmd new-folder-with-selection ${{
-  set -f
-  printf "Directory name: "
-  read newd
-  mkdir -- "$newd"
-  mv -- $fx "$newd"
+    set -f
+    printf "Directory name: "
+    read newd
+    mkdir -- "$newd"
+    mv -- $fx "$newd"
 }}
 
 cmd chmod ${{
-  printf "\nMode Bits: "
-  read ans
-  for file in "$fx"
-  do
-    chmod $ans $file
-  done
-  lf -remote 'send reload'
+    printf "\nMode Bits: "
+    read ans
+    for file in "$fx"
+    do
+        chmod $ans $file
+    done
+    lf -remote 'send reload'
 }}
 
 cmd extract ${{
-  set -f
-  case $f in
-    *.tar.bz|*.tar.bz2|*.tbz|*.tbz2) tar xjvf $f;;
-    *.tar.gz|*.tgz) tar xzvf $f;;
-    *.tar.xz|*.txz) tar xJvf $f;;
-    *.tar) tar xvf $f;;
-    *.zip) unzip $f;;
-    *.rar) unrar x $f;;
-    *.7z) 7z x $f;;
-    *) echo "Unsupported format";;
-  esac
+    set -f
+    case $f in
+        *.tar.bz|*.tar.bz2|*.tbz|*.tbz2) tar xjvf $f;;
+        *.tar.gz|*.tgz) tar xzvf $f;;
+        *.tar.xz|*.txz) tar xJvf $f;;
+        *.tar) tar xvf $f;;
+        *.zip) unzip $f;;
+        *.rar) unrar x $f;;
+        *.7z) 7z x $f;;
+        *) echo "Unsupported format";;
+    esac
 }}
 
 cmd tar ${{
-    set -f
-    mkdir $1
-    cp -r $fx $1
-    tar czf $1.tar.gz $1
-    rm -rf $1
+        set -f
+        mkdir $1
+        cp -r $fx $1
+        tar czf $1.tar.gz $1
+        rm -rf $1
 }}
 
 cmd zip ${{
-    set -f
-    mkdir $1
-    cp -r $fx $1
-    zip -r $1.zip $1
-    rm -rf $1
+        set -f
+        mkdir $1
+        cp -r $fx $1
+        zip -r $1.zip $1
+        rm -rf $1
 }}
 
 cmd delete ${{
-  set -f
-  printf "\n$fx\n"
-  printf "delete?[y/N]"
-  read ans
-  if [[ $ans == "y" ]]; then
-    rm -rf $fx
-  fi
+    set -f
+    printf "\n$fx\n"
+    printf "delete?[y/N]"
+    read ans
+    if [[ $ans == "y" ]]; then
+        rm -rf $fx
+    fi
 }}
 
 cmd trash !{{
-  set -f
-  printf "\nItems to be trashed:\n$fx\n\nTrash? [y/N]"
-  read ans
-  if [[ $ans == "y" ]]; then
-    trash -F $fx && echo "Trash complete!"
-  elif [[ $ans == "n" ]]; then
-    echo "Canceled!"
-  else
-    echo "Failed! Use y to trash."
-  fi
+    set -f
+    printf "\nItems to be trashed:\n$fx\n\nTrash? [y/N]"
+    read ans
+    if [[ $ans == "y" ]]; then
+        trash -F $fx && echo "Trash complete!"
+    elif [[ $ans == "n" ]]; then
+        echo "Canceled!"
+    else
+        echo "Failed! Use y to trash."
+    fi
 }}
 
 cmd select-all :unselect; invert
 
 # Bulk rename on selected files or all the non-hidden files in the current directory if no selection
 cmd bulk-rename ${{
-  old="$(mktemp)"
-  new="$(mktemp)"
-  if [ -n "$fs" ]; then
-    fs="$(basename $fs)"
-  else
-    fs="$(ls)"
-  fi
-  printf '%s\n' "$fs" >"$old"
-  printf '%s\n' "$fs" >"$new"
-  $EDITOR "$new"
-  [ "$(wc -l < "$new")" -ne "$(wc -l < "$old")" ] && exit
-  paste "$old" "$new" | while IFS= read -r names; do
-    src="$(printf '%s' "$names" | cut -f1)"
-    dst="$(printf '%s' "$names" | cut -f2)"
-    if [ "$src" = "$dst" ] || [ -e "$dst" ]; then
-        continue
+    old="$(mktemp)"
+    new="$(mktemp)"
+    if [ -n "$fs" ]; then
+        fs="$(basename $fs)"
+    else
+        fs="$(ls)"
     fi
-    mv -- "$src" "$dst"
-  done
-  rm -- "$old" "$new"
-  lf -remote "send $id unselect"
+    printf '%s\n' "$fs" >"$old"
+    printf '%s\n' "$fs" >"$new"
+    $EDITOR "$new"
+    [ "$(wc -l < "$new")" -ne "$(wc -l < "$old")" ] && exit
+    paste "$old" "$new" | while IFS= read -r names; do
+        src="$(printf '%s' "$names" | cut -f1)"
+        dst="$(printf '%s' "$names" | cut -f2)"
+        if [ "$src" = "$dst" ] || [ -e "$dst" ]; then
+                continue
+        fi
+        mv -- "$src" "$dst"
+    done
+    rm -- "$old" "$new"
+    lf -remote "send $id unselect"
 }}
 
 # Copy the file names (including extension) of the selections separated by \n
 cmd copy-filename ${{
-  names="$(echo $fx | tr ' ' '\n' | xargs -I{} basename {})"
-  echo $names | tr ' ' '\n' | pbcopy
+    names="$(echo $fx | tr ' ' '\n' | xargs -I{} basename {})"
+    echo $names | tr ' ' '\n' | pbcopy
 }}
 
 # Copy the absolute paths of selections separated by \n
 cmd copy-absolute-path ${{
-  echo $fx | tr ' ' '\n' | pbcopy
+    echo $fx | tr ' ' '\n' | pbcopy
 }}
 
-# toggle the selections in fzf
-cmd fzf-select ${{
-  selections=$(eval "fd --max-depth 1 --hidden --follow $FD_EXCLUDE" | fzf \
-      --multi \
-      --header ':: ENTER (toggle the selections), CTRL-R (recursively, no depth limit), CTRL-L (limited to depth 1)' \
-      --bind "ctrl-r:reload(fd --hidden --follow $FD_EXCLUDE),ctrl-l:reload(fd --max-depth 1 --hidden --follow $FD_EXCLUDE)" \
-      --prompt 'Files> ') || true
-  if [[ -n $selections ]]; then
-    # Escape white spaces and format multi-line string to a single line one
-    targets=$(echo "$selections" | sed 's/ /\\ /g' | tr '\n' ' ')
-    lf -remote "send $id toggle $targets"
-  fi
+# Fzf to toggle the selections
+cmd fzf-toggle-select ${{
+    no_depth="/tmp/lf-fzf-toggle-select-no-depth"
+    rm -f $no_depth
+    fd_cmd="fd --max-depth 1 --hidden --follow $FD_EXCLUDE"
+    selections=$(eval "$fd_cmd" | fzf \
+        --multi \
+        --header ':: ENTER (toggle selections), CTRL-T (toggle no-depth/depth-1 traveral)' \
+        --prompt 'Files> ' \
+        --bind "ctrl-t:transform: \
+        [[ ! -e $no_depth ]] && { \
+            touch $no_depth; \
+            echo \"reload(fd --hidden --follow $FD_EXCLUDE)\"; \
+        } || { \
+            rm $no_depth; \
+            echo \"reload($fd_cmd)\"; \
+        }" \
+    ) || true
+    if [[ -n $selections ]]; then
+        # Escape white spaces and format multi-line string to a single line one
+        targets=$(echo "$selections" | sed 's/ /\\ /g' | tr '\n' ' ')
+        cnt=$(echo "$selections" | wc -l)
+        lf -remote "send $id toggle $targets"
+        lf -remote "send $id echo Toggle $cnt selections"
+    fi
 }}
 
-# cd into the selected directory in fzf
+# Fzf: change the current file selection
+cmd fzf-file ${{
+    is_home="/tmp/lf-fzf-file-is-home"
+    rm -f "$is_home"
+    fd_cmd="fd --type f --type l --hidden --follow $FD_EXCLUDE"
+    select=$(eval "$fd_cmd" | fzf \
+        --no-multi \
+        --header ':: CTRL-T (toggle HOME/Current dir)' \
+        --prompt 'Files [Current]> ' \
+        --bind "ctrl-t:transform: \
+        [[ ! -e $is_home ]] && { \
+            touch $is_home; \
+            echo \"reload($fd_cmd . $HOME | sed 's|^$HOME|~|')+change-prompt(Files [HOME]> )\"; \
+        } || { \
+            rm $is_home; \
+            echo \"reload($fd_cmd)+change-prompt(Files [Current]> )\"; \
+        }" \
+    ) || true
+    if [[ -n $select ]]; then
+        lf -remote "send $id select $select"
+    fi
+}}
+
+# Fzf: cd into the selected directory
 cmd fzf-cd ${{
-  is_home="/tmp/lf-fzf-cd-is-home"
-  rm -f "$is_home"
-  fd_cmd="fd --type d --hidden --follow $FD_EXCLUDE"
-  select=$(eval "$fd_cmd" | fzf \
-      --no-multi \
-      --header ':: CTRL-T (switch to HOME/CURRENT)' \
-      --prompt 'Dirs [Current]> ' \
-      --bind "ctrl-t:transform: \
-      [[ ! -e $is_home ]] && { \
-        touch $is_home; \
-        echo \"reload($fd_cmd . $HOME | sed 's|^$HOME|~|')+change-prompt(Dirs [HOME]> )\"; \
-      } || { \
-        rm $is_home; \
-        echo \"reload($fd_cmd)+change-prompt(Dirs [Current]> )\"; \
-      }") || true
-  if [[ -n $select ]]; then
-    lf -remote "send $id cd $select"
-  fi
+    is_home="/tmp/lf-fzf-cd-is-home"
+    rm -f "$is_home"
+    fd_cmd="fd --type d --hidden --follow $FD_EXCLUDE"
+    select=$(eval "$fd_cmd" | fzf \
+        --no-multi \
+        --header ':: CTRL-T (toggle HOME/Current dir)' \
+        --prompt 'Dirs [Current]> ' \
+        --bind "ctrl-t:transform: \
+        [[ ! -e $is_home ]] && { \
+            touch $is_home; \
+            echo \"reload($fd_cmd . $HOME | sed 's|^$HOME|~|')+change-prompt(Dirs [HOME]> )\"; \
+        } || { \
+            rm $is_home; \
+            echo \"reload($fd_cmd)+change-prompt(Dirs [Current]> )\"; \
+        }") || true
+    if [[ -n $select ]]; then
+        lf -remote "send $id cd $select"
+    fi
 }}
 
-# zoxide
+# Zoxide
 cmd z %{{
-  result="$(zoxide query --exclude $PWD $@ | sed 's/\\/\\\\/g;s/"/\\"/g')"
-  lf -remote "send $id cd \"$result\""
+    result="$(zoxide query --exclude $PWD $@ | sed 's/\\/\\\\/g;s/"/\\"/g')"
+    lf -remote "send $id cd \"$result\""
 }}
 
 cmd zi ${{
-  result="$(zoxide query -i | sed 's/\\/\\\\/g;s/"/\\"/g')"
-  lf -remote "send $id cd \"$result\""
+    result="$(zoxide query -i | sed 's/\\/\\\\/g;s/"/\\"/g')"
+    lf -remote "send $id cd \"$result\""
 }}
 
 # Git for dotfiles
 cmd dot ${{
-  git --git-dir=/Users/rockyzhang/dotfiles/ --work-tree=/Users/rockyzhang $@
+    git --git-dir=/Users/rockyzhang/dotfiles/ --work-tree=/Users/rockyzhang $@
 }}
 
 # ========== Mappings ==========
@@ -205,8 +241,10 @@ cmd dot ${{
 map gh
 map d
 map y
-map <space>
 map zh
+
+# <space> is used as the leader key
+map <space>
 
 map z. set hidden!
 map <tab> :toggle; down
@@ -219,7 +257,8 @@ map d delete
 map T trash
 # list the size of each item in the current directory
 map U !printf "\n"; du -csh *
-map <c-f> fzf-select
+map <c-t> fzf-toggle-select
+map <c-f> fzf-file
 map <c-j> fzf-cd
 # give a name and then make a directory
 map <c-n> push :mkdir<space>
@@ -240,7 +279,6 @@ map rn push A<c-u> # rename the filename
 map re push A<c-f><c-k> # rename the extension
 map <c-r> bulk-rename
 
-# Use <space> as the leader key
 # compress (give a name like abc and it will compress the selected items to abc.zip)
 map <space>c push :zip<space>
 # extract
